"""Generate LaTeX macros from computed results.

The paper inputs the generated file so its numbers always match the
pipeline output; regenerate with `uv run gadget-analysis`.
"""

from pathlib import Path


def _macros(results: dict) -> dict[str, str]:
    x, y = results["x"], results["y"]
    pearson = results["bivariate"]["pearson"]
    regression = results["bivariate"]["regression"]
    counts = results["probability"]["counts"]
    probabilities = results["probability"]["probabilities"]
    descriptives_x, descriptives_y = x["descriptives"], y["descriptives"]
    n_x_items = len(x["item_total_correlations"])
    n_y_items = len(y["item_total_correlations"])
    significance = "0.000" if pearson["p"] < 0.001 else f"{pearson['p']:.3f}"
    return {
        "resN": f"{results['data']['n']}",
        "resNItems": f"{n_x_items + n_y_items}",
        "resNXItems": f"{n_x_items}",
        "resNYItems": f"{n_y_items}",
        "resXRangeMin": f"{n_x_items}",
        "resXRangeMax": f"{n_x_items * 5}",
        "resYRangeMin": f"{n_y_items}",
        "resYRangeMax": f"{n_y_items * 5}",
        "resXMean": f"{descriptives_x['mean']:.2f}",
        "resYMean": f"{descriptives_y['mean']:.2f}",
        "resXMedian": f"{descriptives_x['median']:.0f}",
        "resYMedian": f"{descriptives_y['median']:.0f}",
        "resXSd": f"{descriptives_x['sd']:.2f}",
        "resYSd": f"{descriptives_y['sd']:.2f}",
        "resXMin": f"{descriptives_x['min']}",
        "resXMax": f"{descriptives_x['max']}",
        "resYMin": f"{descriptives_y['min']}",
        "resYMax": f"{descriptives_y['max']}",
        "resR": f"{pearson['r']:.3f}",
        "resSig": significance,
        "resRSquared": f"{regression['r2']:.4f}",
        "resRSquaredPct": f"{regression['r2'] * 100:.2f}",
        "resUnexplainedPct": f"{(1 - regression['r2']) * 100:.2f}",
        "resT": f"{regression['t']:.3f}",
        "resF": f"{regression['f']:.3f}",
        "resXNormW": f"{x['normality']['w']:.4f}",
        "resXNormP": f"{x['normality']['p']:.4f}",
        "resYNormW": f"{y['normality']['w']:.4f}",
        "resYNormP": f"{y['normality']['p']:.4f}",
        "resAlphaX": f"{x['cronbach_alpha']:.4f}",
        "resAlphaY": f"{y['cronbach_alpha']:.4f}",
        "resHighX": f"{counts['high_x']}",
        "resHighY": f"{counts['high_y']}",
        "resBoth": f"{counts['both']}",
        "resPA": f"{probabilities['p_a'] * 100:.2f}",
        "resPB": f"{probabilities['p_b'] * 100:.2f}",
        "resPAB": f"{probabilities['p_both'] * 100:.2f}",
        "resPBGivenA": f"{probabilities['p_b_given_a'] * 100:.2f}",
        "resPARatio": f"{probabilities['p_a']:.4f}",
        "resPBRatio": f"{probabilities['p_b']:.4f}",
        "resPABRatio": f"{probabilities['p_both']:.4f}",
        "resPBGivenARatio": f"{probabilities['p_b_given_a']:.4f}",
    }


def format_macros(macros: dict[str, str]) -> str:
    lines = [
        "% Generated by gadget-analysis from results/results.json.",
        "% Do not edit by hand; rerun `uv run gadget-analysis` instead.",
        "",
    ]
    lines.extend(f"\\newcommand{{\\{name}}}{{{value}}}" for name, value in macros.items())
    return "\n".join(lines) + "\n"


def write_latex_macros(results: dict, path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(format_macros(_macros(results)))
    return path
